# Generated by Django 4.2.3 on 2024-04-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='question',
        ),
    ]
