# Generated by Django 4.2.3 on 2024-04-28 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_class_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
