# Generated by Django 4.2.3 on 2024-05-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_quiz_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='question',
            field=models.TextField(),
        ),
    ]
