# Generated by Django 4.2.3 on 2024-06-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_quiz_question1_alter_quiz_question2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='open_question_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question7',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question8',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question9',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
