# Generated by Django 4.2.3 on 2024-06-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_quiz_answer7_quiz_answer8_quiz_answer9_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question7',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question8',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question9',
            field=models.CharField(max_length=255),
        ),
    ]
